# Generated by Django 6.0.8 on 2026-08-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
