# Generated by Django 6.0.8 on 2026-09-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='applications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
