# Generated by Django 6.0.8 on 2026-09-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Short unique code, e.g. MECH, VC, REG, RC-BATHINDA', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('TEACHING_DEPT', 'Teaching Department'), ('RESEARCH_CENTRE', 'Research Centre'), ('REGIONAL_CENTRE', 'Regional Centre'), ('CONSTITUENT_COLLEGE', 'Constituent College'), ('NEIGHBOURHOOD_CAMPUS', 'Neighbourhood Campus'), ('AFFILIATED_COLLEGE', 'Affiliated College'), ('ADMIN_OFFICE', 'Administrative / Non-Teaching Office')], max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text="e.g. a department's parent could be its Regional Centre; an office's parent could be the Vice-Chancellor's office.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.orgunit')),
            ],
            options={
                'verbose_name': 'Organisation Unit',
                'verbose_name_plural': 'Organisation Units',
                'ordering': ['unit_type', 'name'],
            },
        ),
    ]
