# Generated by Django 6.0.8 on 2026-09-13 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='e.g. CS201, MECH-LAB-3', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('semester_number', models.PositiveSmallIntegerField(help_text='Which semester of the programme this is normally taken in')),
                ('credits', models.PositiveSmallIntegerField(default=4)),
                ('course_type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('LAB', 'Lab / Practical'), ('PROJECT', 'Project')], default='CORE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.programme')),
            ],
            options={
                'ordering': ['programme__code', 'semester_number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('DROPPED', 'Dropped')], default='REGISTERED', max_length=20)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_registrations', to='academics.academicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academics.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_session__start_date', 'course__code'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course', 'academic_session'), name='unique_registration_per_student_course_session')],
            },
        ),
    ]
