# Generated by Django 6.0.8 on 2026-09-13 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MID_SEMESTER', 'Mid Semester'), ('END_SEMESTER', 'End Semester'), ('INTERNAL', 'Internal Assessment'), ('SUPPLEMENTARY', 'Supplementary / Backlog')], default='MID_SEMESTER', max_length=20)),
                ('exam_date', models.DateField()),
                ('max_marks', models.PositiveSmallIntegerField(default=100)),
                ('passing_marks', models.PositiveSmallIntegerField(default=40)),
                ('min_attendance_percent', models.PositiveSmallIntegerField(default=75, help_text='Minimum attendance % required to be eligible to sit this exam.')),
                ('is_published', models.BooleanField(default=False, help_text='Students can only see their marks once this is checked.')),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.academicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.course')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('attendance_percent_snapshot', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.courseregistration')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.exam')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('course', 'academic_session', 'exam_type'), name='unique_exam_per_course_session_type'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'course_registration'), name='unique_result_per_exam_per_registration'),
        ),
    ]
