# Generated by Django 6.0.8 on 2026-09-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_signature'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text='The department / college / regional centre / office this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.orgunit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='Mechanical Engineering', help_text="Legacy free-text field, kept so old data still works. New code should use 'org_unit' instead.", max_length=120),
        ),
    ]
