# Generated by Django 6.0.8 on 2026-09-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', help_text="Legacy free-text field, kept so old data still works. New code should use 'org_unit' instead.", max_length=120),
        ),
    ]
