# Generated by Django 6.0.8 on 2026-09-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
