# Generated by Django 6.0.8 on 2026-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_org_unit_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, help_text="Job title for display only (e.g. 'Registrar', 'Assistant Professor', 'Section Officer') - separate from 'role', which controls what they can do in the app.", max_length=150),
        ),
    ]
