# Generated by Django 6.0.8 on 2026-09-15 11:57

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, help_text='Allowed: PDF, DOC/DOCX, XLS/XLSX, JPG, JPEG, PNG (max 15 MB).', null=True, upload_to='announcements/%Y/%m/', validators=[common.validators.validate_upload_file]),
        ),
    ]
