# Generated by Django 6.0.8 on 2026-09-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='route_to_admin_office',
            field=models.BooleanField(default=False, help_text="If checked, this application type is routed to a university-wide administrative office (e.g. Finance, Registrar) matching the role above, instead of someone in the applicant's own department. Use this for things like Purchase Requests that always go to a central office."),
        ),
    ]
