# Generated by Django 6.0.8 on 2026-09-13 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2026-27', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='e.g. BTECH-MECH, MSC-CHEM', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD / Research'), ('DIPLOMA', 'Diploma / Certificate')], max_length=10)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('total_semesters', models.PositiveSmallIntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(limit_choices_to={'unit_type__in': ['TEACHING_DEPT', 'CONSTITUENT_COLLEGE', 'AFFILIATED_COLLEGE']}, on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='organizations.orgunit')),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.PositiveSmallIntegerField(help_text="Year the student's batch started, e.g. 2026")),
                ('roll_number', models.CharField(blank=True, max_length=40)),
                ('current_semester', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed / Graduated'), ('WITHDRAWN', 'Withdrawn'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.programme')),
            ],
            options={
                'ordering': ['-academic_session__start_date', 'roll_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('roll_number', ''), _negated=True), fields=('programme', 'roll_number'), name='unique_roll_number_per_programme')],
            },
        ),
    ]
